// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: sandwich.flex

import java_cup.runtime.*;
      

@SuppressWarnings("fallthrough")
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\12\u1f00\1\u2000\1\u2100\1\u2200\1\u1f00\1\u2300"+
    "\1\u2400\2\u1f00\31\u0100\1\u2500\121\u0100\1\u2600\4\u0100\1\u2700"+
    "\1\u0100\1\u2800\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\53\u0100"+
    "\1\u2e00\41\u1f00\1\u0100\1\u2f00\1\u3000\1\u0100\1\u3100\1\u3200"+
    "\1\u3300\1\u3400\1\u1f00\1\u3500\1\u3600\1\u3700\1\u3800\1\u0100"+
    "\1\u3900\1\u3a00\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u1f00"+
    "\1\u4000\1\u4100\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700"+
    "\1\u4800\1\u4900\1\u4a00\1\u4b00\1\u1f00\1\u4c00\1\u4d00\1\u4e00"+
    "\1\u1f00\3\u0100\1\u4f00\1\u5000\1\u5100\12\u1f00\4\u0100\1\u5200"+
    "\17\u1f00\2\u0100\1\u5300\41\u1f00\2\u0100\1\u5400\1\u5500\2\u1f00"+
    "\1\u5600\1\u5700\27\u0100\1\u5800\2\u0100\1\u5900\45\u1f00\1\u0100"+
    "\1\u5a00\1\u5b00\11\u1f00\1\u5c00\27\u1f00\1\u5d00\1\u5e00\1\u5f00"+
    "\1\u6000\11\u1f00\1\u6100\1\u6200\5\u1f00\1\u6300\1\u6400\4\u1f00"+
    "\1\u6500\21\u1f00\246\u0100\1\u6600\20\u0100\1\u6700\1\u6800\25\u0100"+
    "\1\u6900\34\u0100\1\u6a00\14\u1f00\2\u0100\1\u6b00\u0e05\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\4"+
    "\1\0\1\5\1\0\1\6\2\0\1\7\2\0\1\10"+
    "\1\0\1\11\1\0\1\12\1\13\3\14\1\15\6\14"+
    "\1\16\2\0\1\17\3\0\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\21\1\27\1\21\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\21\1\36\1\37\1\40"+
    "\1\41\2\21\1\42\1\43\1\21\1\44\1\0\1\45"+
    "\1\0\1\46\1\0\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\21\1\60\1\61\1\62"+
    "\1\63\1\64\1\65\1\21\1\66\1\67\1\70\1\71"+
    "\3\21\1\72\1\73\57\0\1\21\2\0\1\74\2\0"+
    "\1\75\2\0\1\76\1\0\1\21\4\0\1\21\5\0"+
    "\2\21\1\77\1\100\23\21\1\0\37\21\1\0\u01ca\21"+
    "\4\0\14\21\16\0\5\21\7\0\1\21\1\0\1\21"+
    "\201\0\5\21\1\0\2\21\2\0\4\21\1\0\1\21"+
    "\6\0\1\21\1\0\3\21\1\0\1\21\1\0\24\21"+
    "\1\0\123\21\1\0\213\21\10\0\246\21\1\0\46\21"+
    "\2\0\1\21\6\0\51\21\107\0\33\21\4\0\4\21"+
    "\55\0\53\21\43\0\2\21\1\0\143\21\1\0\1\21"+
    "\17\0\2\21\7\0\2\21\12\0\3\21\2\0\1\21"+
    "\20\0\1\21\1\0\36\21\35\0\131\21\13\0\1\21"+
    "\30\0\41\21\11\0\2\21\4\0\1\21\5\0\26\21"+
    "\4\0\1\21\11\0\1\21\3\0\1\21\27\0\31\21"+
    "\7\0\13\21\65\0\25\21\1\0\10\21\106\0\66\21"+
    "\3\0\1\21\22\0\1\21\7\0\12\21\17\0\20\21"+
    "\4\0\10\21\2\0\2\21\2\0\26\21\1\0\7\21"+
    "\1\0\1\21\3\0\4\21\3\0\1\21\20\0\1\21"+
    "\15\0\2\21\1\0\3\21\16\0\2\21\12\0\1\21"+
    "\10\0\6\21\4\0\2\21\2\0\26\21\1\0\7\21"+
    "\1\0\2\21\1\0\2\21\1\0\2\21\37\0\4\21"+
    "\1\0\1\21\23\0\3\21\20\0\11\21\1\0\3\21"+
    "\1\0\26\21\1\0\7\21\1\0\2\21\1\0\5\21"+
    "\3\0\1\21\22\0\1\21\17\0\2\21\27\0\1\21"+
    "\13\0\10\21\2\0\2\21\2\0\26\21\1\0\7\21"+
    "\1\0\2\21\1\0\5\21\3\0\1\21\36\0\2\21"+
    "\1\0\3\21\17\0\1\21\21\0\1\21\1\0\6\21"+
    "\3\0\3\21\1\0\4\21\3\0\2\21\1\0\1\21"+
    "\1\0\2\21\3\0\2\21\3\0\3\21\3\0\14\21"+
    "\26\0\1\21\64\0\10\21\1\0\3\21\1\0\27\21"+
    "\1\0\20\21\3\0\1\21\32\0\3\21\5\0\2\21"+
    "\36\0\1\21\4\0\10\21\1\0\3\21\1\0\27\21"+
    "\1\0\12\21\1\0\5\21\3\0\1\21\40\0\1\21"+
    "\1\0\2\21\17\0\2\21\22\0\10\21\1\0\3\21"+
    "\1\0\51\21\2\0\1\21\20\0\1\21\5\0\3\21"+
    "\10\0\3\21\30\0\6\21\5\0\22\21\3\0\30\21"+
    "\1\0\11\21\1\0\1\21\2\0\7\21\72\0\60\21"+
    "\1\0\2\21\14\0\7\21\72\0\2\21\1\0\1\21"+
    "\1\0\5\21\1\0\30\21\1\0\1\21\1\0\12\21"+
    "\1\0\2\21\11\0\1\21\2\0\5\21\1\0\1\21"+
    "\25\0\4\21\40\0\1\21\77\0\10\21\1\0\44\21"+
    "\33\0\5\21\163\0\53\21\24\0\1\21\20\0\6\21"+
    "\4\0\4\21\3\0\1\21\3\0\2\21\7\0\3\21"+
    "\4\0\15\21\14\0\1\21\21\0\46\21\1\0\1\21"+
    "\5\0\1\21\2\0\53\21\1\0\115\21\1\0\4\21"+
    "\2\0\7\21\1\0\1\21\1\0\4\21\2\0\51\21"+
    "\1\0\4\21\2\0\41\21\1\0\4\21\2\0\7\21"+
    "\1\0\1\21\1\0\4\21\2\0\17\21\1\0\71\21"+
    "\1\0\4\21\2\0\103\21\45\0\20\21\20\0\126\21"+
    "\2\0\6\21\3\0\u016c\21\2\0\21\21\1\0\32\21"+
    "\5\0\113\21\6\0\10\21\7\0\15\21\1\0\4\21"+
    "\16\0\22\21\16\0\22\21\16\0\15\21\1\0\3\21"+
    "\17\0\64\21\43\0\1\21\4\0\1\21\103\0\131\21"+
    "\7\0\5\21\2\0\42\21\1\0\1\21\5\0\106\21"+
    "\12\0\37\21\61\0\36\21\2\0\5\21\13\0\54\21"+
    "\4\0\32\21\66\0\27\21\11\0\65\21\122\0\1\21"+
    "\135\0\57\21\21\0\7\21\67\0\36\21\15\0\2\21"+
    "\12\0\54\21\32\0\44\21\51\0\3\21\12\0\44\21"+
    "\2\0\11\21\7\0\53\21\2\0\3\21\51\0\4\21"+
    "\1\0\6\21\1\0\2\21\3\0\1\21\5\0\300\21"+
    "\100\0\26\21\2\0\6\21\2\0\46\21\2\0\6\21"+
    "\2\0\10\21\1\0\1\21\1\0\1\21\1\0\1\21"+
    "\1\0\37\21\2\0\65\21\1\0\7\21\1\0\1\21"+
    "\3\0\3\21\1\0\7\21\3\0\4\21\2\0\6\21"+
    "\4\0\15\21\5\0\3\21\1\0\7\21\164\0\1\21"+
    "\15\0\1\21\20\0\15\21\145\0\1\21\4\0\1\21"+
    "\2\0\12\21\1\0\1\21\3\0\5\21\6\0\1\21"+
    "\1\0\1\21\1\0\1\21\1\0\4\21\1\0\13\21"+
    "\2\0\4\21\5\0\5\21\4\0\1\21\64\0\2\21"+
    "\u017b\0\57\21\1\0\57\21\1\0\205\21\6\0\4\21"+
    "\3\0\2\21\14\0\46\21\1\0\1\21\5\0\1\21"+
    "\2\0\70\21\7\0\1\21\20\0\27\21\11\0\7\21"+
    "\1\0\7\21\1\0\7\21\1\0\7\21\1\0\7\21"+
    "\1\0\7\21\1\0\7\21\1\0\7\21\120\0\1\21"+
    "\325\0\2\21\52\0\5\21\5\0\2\21\4\0\126\21"+
    "\6\0\3\21\1\0\132\21\1\0\4\21\5\0\53\21"+
    "\1\0\136\21\21\0\33\21\65\0\306\21\112\0\360\21"+
    "\20\0\215\21\103\0\56\21\2\0\15\21\3\0\20\21"+
    "\12\0\2\21\24\0\57\21\20\0\37\21\2\0\106\21"+
    "\61\0\11\21\2\0\147\21\2\0\65\21\2\0\5\21"+
    "\60\0\13\21\1\0\3\21\1\0\4\21\1\0\27\21"+
    "\35\0\64\21\16\0\62\21\76\0\6\21\3\0\1\21"+
    "\1\0\2\21\13\0\34\21\12\0\27\21\31\0\35\21"+
    "\7\0\57\21\34\0\1\21\20\0\5\21\1\0\12\21"+
    "\12\0\5\21\1\0\51\21\27\0\3\21\1\0\10\21"+
    "\24\0\27\21\3\0\1\21\3\0\62\21\1\0\1\21"+
    "\3\0\2\21\2\0\5\21\2\0\1\21\1\0\1\21"+
    "\30\0\3\21\2\0\13\21\7\0\3\21\14\0\6\21"+
    "\2\0\6\21\2\0\6\21\11\0\7\21\1\0\7\21"+
    "\1\0\53\21\1\0\14\21\10\0\163\21\35\0\244\21"+
    "\14\0\27\21\4\0\61\21\4\0\156\21\2\0\152\21"+
    "\46\0\7\21\14\0\5\21\5\0\1\21\1\0\12\21"+
    "\1\0\15\21\1\0\5\21\1\0\1\21\1\0\2\21"+
    "\1\0\2\21\1\0\154\21\41\0\153\21\22\0\100\21"+
    "\2\0\66\21\50\0\14\21\164\0\5\21\1\0\207\21"+
    "\44\0\32\21\6\0\32\21\13\0\131\21\3\0\6\21"+
    "\2\0\6\21\2\0\6\21\2\0\3\21\43\0\14\21"+
    "\1\0\32\21\1\0\23\21\1\0\2\21\1\0\17\21"+
    "\2\0\16\21\42\0\173\21\205\0\35\21\3\0\61\21"+
    "\57\0\40\21\15\0\24\21\1\0\10\21\6\0\46\21"+
    "\12\0\36\21\2\0\44\21\4\0\10\21\60\0\236\21"+
    "\22\0\44\21\4\0\44\21\4\0\50\21\10\0\64\21"+
    "\234\0\67\21\11\0\26\21\12\0\10\21\230\0\6\21"+
    "\2\0\1\21\1\0\54\21\1\0\2\21\3\0\1\21"+
    "\2\0\27\21\12\0\27\21\11\0\37\21\101\0\23\21"+
    "\1\0\2\21\12\0\26\21\12\0\32\21\106\0\70\21"+
    "\6\0\2\21\100\0\1\21\17\0\4\21\1\0\3\21"+
    "\1\0\35\21\52\0\35\21\3\0\35\21\43\0\10\21"+
    "\1\0\34\21\33\0\66\21\12\0\26\21\12\0\23\21"+
    "\15\0\22\21\156\0\111\21\67\0\63\21\15\0\63\21"+
    "\15\0\44\21\334\0\35\21\12\0\1\21\10\0\26\21"+
    "\232\0\27\21\14\0\65\21\113\0\55\21\40\0\31\21"+
    "\32\0\44\21\35\0\1\21\13\0\43\21\3\0\1\21"+
    "\14\0\60\21\16\0\4\21\25\0\1\21\1\0\1\21"+
    "\43\0\22\21\1\0\31\21\124\0\7\21\1\0\1\21"+
    "\1\0\4\21\1\0\17\21\1\0\12\21\7\0\57\21"+
    "\46\0\10\21\2\0\2\21\2\0\26\21\1\0\7\21"+
    "\1\0\2\21\1\0\5\21\3\0\1\21\22\0\1\21"+
    "\14\0\5\21\236\0\65\21\22\0\4\21\24\0\1\21"+
    "\40\0\60\21\24\0\2\21\1\0\1\21\270\0\57\21"+
    "\51\0\4\21\44\0\60\21\24\0\1\21\73\0\53\21"+
    "\15\0\1\21\107\0\33\21\345\0\54\21\164\0\100\21"+
    "\37\0\1\21\240\0\10\21\2\0\47\21\20\0\1\21"+
    "\1\0\1\21\34\0\1\21\12\0\50\21\7\0\1\21"+
    "\25\0\1\21\13\0\56\21\23\0\1\21\42\0\71\21"+
    "\7\0\11\21\1\0\45\21\21\0\1\21\61\0\36\21"+
    "\160\0\7\21\1\0\2\21\1\0\46\21\25\0\1\21"+
    "\31\0\6\21\1\0\2\21\1\0\40\21\16\0\1\21"+
    "\u0147\0\23\21\15\0\232\21\346\0\304\21\274\0\57\21"+
    "\321\0\107\21\271\0\71\21\7\0\37\21\161\0\36\21"+
    "\22\0\60\21\20\0\4\21\37\0\25\21\5\0\23\21"+
    "\260\0\100\21\200\0\113\21\5\0\1\21\102\0\15\21"+
    "\100\0\2\21\1\0\1\21\34\0\370\21\10\0\363\21"+
    "\15\0\37\21\61\0\3\21\21\0\4\21\10\0\u018c\21"+
    "\4\0\153\21\5\0\15\21\3\0\11\21\7\0\12\21"+
    "\146\0\125\21\1\0\107\21\1\0\2\21\2\0\1\21"+
    "\2\0\2\21\2\0\4\21\1\0\14\21\1\0\1\21"+
    "\1\0\7\21\1\0\101\21\1\0\4\21\2\0\10\21"+
    "\1\0\7\21\1\0\34\21\1\0\4\21\1\0\5\21"+
    "\1\0\1\21\3\0\7\21\1\0\u0154\21\2\0\31\21"+
    "\1\0\31\21\1\0\37\21\1\0\31\21\1\0\37\21"+
    "\1\0\31\21\1\0\37\21\1\0\31\21\1\0\37\21"+
    "\1\0\31\21\1\0\10\21\64\0\55\21\12\0\7\21"+
    "\20\0\1\21\u0171\0\54\21\24\0\305\21\73\0\104\21"+
    "\7\0\1\21\264\0\4\21\1\0\33\21\1\0\2\21"+
    "\1\0\1\21\2\0\1\21\1\0\12\21\1\0\4\21"+
    "\1\0\1\21\1\0\1\21\6\0\1\21\4\0\1\21"+
    "\1\0\1\21\1\0\1\21\1\0\3\21\1\0\2\21"+
    "\1\0\1\21\2\0\1\21\1\0\1\21\1\0\1\21"+
    "\1\0\1\21\1\0\1\21\1\0\2\21\1\0\1\21"+
    "\2\0\4\21\1\0\7\21\1\0\4\21\1\0\4\21"+
    "\1\0\1\21\1\0\12\21\1\0\21\21\5\0\3\21"+
    "\1\0\5\21\1\0\21\21\104\0\327\21\51\0\65\21"+
    "\13\0\336\21\2\0\u0182\21\16\0\u0131\21\37\0\36\21"+
    "\342\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[27648];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\3\1\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\2\13\1\14"+
    "\7\13\1\15\1\16\4\13\1\14\1\13\1\14\3\13"+
    "\1\14\1\13\1\0\1\17\1\5\4\0\1\20\1\0"+
    "\25\13\1\0\4\13\1\14\6\13\1\0\1\5\1\0"+
    "\2\21\1\22\2\0\2\20\16\13\1\23\11\13\1\0"+
    "\1\14\10\13\1\5\2\0\1\20\11\13\1\24\1\13"+
    "\1\0\11\13\1\25\1\0\5\13\1\14\1\13\1\5"+
    "\1\0\7\13\1\26\1\13\2\0\2\13\1\27\6\13"+
    "\1\0\6\13\1\5\11\13\2\0\1\30\1\13\1\31"+
    "\1\13\1\32\1\13\1\33\1\0\2\13\1\14\1\13"+
    "\1\0\5\13\2\0\3\13\1\34\2\13\1\35\1\0"+
    "\4\13\1\0\2\13\2\0\1\35\1\13\1\0\2\13"+
    "\1\26\1\36\1\0\1\31\1\37\1\0\1\40\1\13"+
    "\1\0\1\37\1\13\1\0\1\41\10\0\1\42";

  private static int [] zzUnpackAction() {
    int [] result = new int[264];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\101\0\202\0\101\0\303\0\u0104\0\u0145\0\u0186"+
    "\0\101\0\101\0\u01c7\0\101\0\101\0\u0208\0\u0249\0\u028a"+
    "\0\u02cb\0\u030c\0\u034d\0\u038e\0\u03cf\0\u0410\0\u0451\0\u0492"+
    "\0\u04d3\0\101\0\101\0\u0514\0\u0555\0\u0596\0\u05d7\0\u0618"+
    "\0\u0659\0\u069a\0\u06db\0\u071c\0\u075d\0\u079e\0\u07df\0\u0104"+
    "\0\101\0\u0820\0\u0861\0\u08a2\0\u08e3\0\u0924\0\u0965\0\u09a6"+
    "\0\u09e7\0\u0a28\0\u0a69\0\u0aaa\0\u0aeb\0\u0b2c\0\u0b6d\0\u0bae"+
    "\0\u0bef\0\u0c30\0\u0c71\0\u0cb2\0\u0cf3\0\u0d34\0\u0d75\0\u0db6"+
    "\0\u0df7\0\u0e38\0\u0e79\0\u0eba\0\u0efb\0\u0f3c\0\u0f7d\0\u0fbe"+
    "\0\u0fff\0\u1040\0\u0208\0\u1081\0\u10c2\0\u1103\0\u1144\0\u1185"+
    "\0\u11c6\0\u1207\0\u1248\0\u1289\0\u08a2\0\u12ca\0\u130b\0\u134c"+
    "\0\u138d\0\101\0\u13ce\0\u140f\0\u1450\0\u1491\0\u14d2\0\u1513"+
    "\0\u1554\0\u1595\0\u15d6\0\u1617\0\u1658\0\u1699\0\u16da\0\u171b"+
    "\0\u175c\0\u0208\0\u179d\0\u17de\0\u181f\0\u1860\0\u18a1\0\u18e2"+
    "\0\u1923\0\u1964\0\u19a5\0\u19e6\0\101\0\u1a27\0\u1a68\0\u1aa9"+
    "\0\u1aea\0\u1b2b\0\u1b6c\0\u1bad\0\u1bee\0\u1c2f\0\u1c70\0\u1cb1"+
    "\0\u1cf2\0\u1d33\0\u1d74\0\u1db5\0\u1df6\0\u1e37\0\u1e78\0\u1eb9"+
    "\0\u1efa\0\u1f3b\0\u0208\0\u1f7c\0\u1fbd\0\u1ffe\0\u203f\0\u2080"+
    "\0\u20c1\0\u2102\0\u2143\0\u2184\0\u21c5\0\u2206\0\u0208\0\u2247"+
    "\0\u2288\0\u22c9\0\u230a\0\u234b\0\u238c\0\u23cd\0\u240e\0\u244f"+
    "\0\u13ce\0\u2490\0\u24d1\0\u2512\0\u2553\0\u2594\0\u25d5\0\u2616"+
    "\0\u0208\0\u2657\0\u2698\0\u26d9\0\u271a\0\u275b\0\u0208\0\u279c"+
    "\0\u27dd\0\u281e\0\u285f\0\u28a0\0\u28e1\0\u2922\0\u2963\0\u29a4"+
    "\0\u23cd\0\u0618\0\u069a\0\u29e5\0\101\0\u2a26\0\u2a67\0\u2aa8"+
    "\0\u2ae9\0\u2b2a\0\u2b6b\0\u2bac\0\u2bed\0\u2c2e\0\u2c6f\0\u2cb0"+
    "\0\u0208\0\u2cf1\0\u0208\0\u2d32\0\u0208\0\u2d73\0\u0208\0\u2db4"+
    "\0\u2df5\0\u2e36\0\u2e77\0\u2eb8\0\u2ef9\0\u2f3a\0\u2f7b\0\u2fbc"+
    "\0\u2ffd\0\u303e\0\u307f\0\u30c0\0\u3101\0\u3142\0\u3183\0\101"+
    "\0\u31c4\0\u3205\0\u0208\0\u3246\0\u3287\0\u32c8\0\u3309\0\u334a"+
    "\0\u338b\0\u33cc\0\u340d\0\u344e\0\u348f\0\101\0\u34d0\0\u3511"+
    "\0\u3552\0\u3593\0\101\0\u0208\0\u35d4\0\101\0\u0208\0\u3615"+
    "\0\u0208\0\u3656\0\u3697\0\101\0\u36d8\0\u3719\0\u0208\0\u375a"+
    "\0\u379b\0\u37dc\0\u381d\0\u385e\0\u389f\0\u38e0\0\u3921\0\101";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[264];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\3\1\6\1\7\1\2"+
    "\1\10\1\11\1\12\1\2\2\13\1\14\1\15\2\16"+
    "\1\17\1\20\1\21\1\22\1\16\1\23\1\24\1\16"+
    "\1\25\1\16\1\26\1\27\1\30\1\16\1\31\3\16"+
    "\1\32\1\33\1\2\1\34\1\16\1\35\1\36\1\37"+
    "\1\16\1\40\2\16\1\41\1\42\1\43\2\16\1\44"+
    "\2\16\1\45\1\46\2\16\3\2\1\47\1\16\102\0"+
    "\1\3\2\0\1\3\76\0\1\4\76\0\5\50\1\51"+
    "\73\50\6\0\1\7\102\0\1\52\74\0\1\53\4\0"+
    "\1\54\1\55\1\56\2\13\40\0\1\57\3\0\1\60"+
    "\36\0\24\16\3\0\25\16\3\0\2\16\20\0\24\16"+
    "\3\0\1\61\14\16\1\62\7\16\3\0\2\16\20\0"+
    "\7\16\1\63\14\16\3\0\4\16\1\64\3\16\1\65"+
    "\14\16\3\0\2\16\20\0\22\16\1\66\1\16\3\0"+
    "\14\16\1\67\10\16\3\0\2\16\20\0\1\70\23\16"+
    "\3\0\25\16\3\0\2\16\20\0\13\16\1\71\10\16"+
    "\3\0\25\16\3\0\2\16\20\0\24\16\3\0\2\16"+
    "\1\72\22\16\3\0\2\16\20\0\4\16\1\73\14\16"+
    "\1\74\2\16\3\0\4\16\1\75\20\16\3\0\2\16"+
    "\20\0\24\16\3\0\1\16\1\76\15\16\1\77\5\16"+
    "\3\0\2\16\20\0\1\100\23\16\3\0\15\16\1\101"+
    "\1\16\1\102\5\16\3\0\2\16\20\0\4\16\1\103"+
    "\17\16\3\0\4\16\1\104\20\16\3\0\2\16\20\0"+
    "\24\16\3\0\10\16\1\105\14\16\3\0\2\16\4\0"+
    "\1\106\13\0\24\16\3\0\25\16\3\0\2\16\20\0"+
    "\24\16\3\0\13\16\1\107\1\16\1\110\4\16\1\111"+
    "\2\16\3\0\2\16\20\0\24\16\3\0\4\16\1\64"+
    "\20\16\3\0\2\16\20\0\24\16\3\0\14\16\1\67"+
    "\10\16\3\0\2\16\20\0\24\16\3\0\17\16\1\112"+
    "\5\16\3\0\2\16\20\0\24\16\3\0\6\16\1\113"+
    "\1\16\1\114\14\16\3\0\2\16\20\0\24\16\3\0"+
    "\10\16\1\115\14\16\3\0\2\16\20\0\24\16\3\0"+
    "\4\16\1\75\3\16\1\116\1\16\1\113\12\16\3\0"+
    "\2\16\20\0\24\16\3\0\15\16\1\117\1\16\1\102"+
    "\5\16\3\0\2\16\20\0\24\16\3\0\1\120\24\16"+
    "\3\0\2\16\20\0\24\16\3\0\14\16\1\121\10\16"+
    "\3\0\2\16\20\0\24\16\3\0\25\16\1\0\1\122"+
    "\1\0\2\16\10\0\1\123\104\0\2\124\40\0\1\57"+
    "\3\0\1\60\32\0\2\125\77\0\2\126\77\0\2\127"+
    "\67\0\1\130\7\0\2\131\63\0\57\132\1\133\1\132"+
    "\1\0\17\132\20\0\24\16\3\0\12\16\1\134\6\16"+
    "\1\135\3\16\3\0\2\16\20\0\24\16\3\0\12\16"+
    "\1\136\12\16\3\0\2\16\20\0\5\16\1\137\16\16"+
    "\3\0\25\16\3\0\2\16\20\0\24\16\3\0\20\16"+
    "\1\140\4\16\3\0\2\16\20\0\24\16\3\0\5\16"+
    "\1\141\17\16\3\0\2\16\20\0\15\16\1\142\6\16"+
    "\3\0\25\16\3\0\2\16\20\0\24\16\3\0\21\16"+
    "\1\143\3\16\3\0\2\16\20\0\2\16\1\144\21\16"+
    "\3\0\25\16\3\0\2\16\20\0\6\16\1\145\15\16"+
    "\3\0\25\16\3\0\2\16\20\0\24\16\3\0\1\146"+
    "\24\16\3\0\2\16\20\0\3\16\1\147\20\16\3\0"+
    "\25\16\3\0\2\16\20\0\23\16\1\150\3\0\25\16"+
    "\3\0\2\16\20\0\24\16\3\0\17\16\1\151\5\16"+
    "\3\0\2\16\20\0\24\16\3\0\20\16\1\152\4\16"+
    "\3\0\2\16\20\0\24\16\3\0\10\16\1\153\14\16"+
    "\3\0\2\16\20\0\17\16\1\154\4\16\3\0\25\16"+
    "\3\0\2\16\20\0\24\16\3\0\17\16\1\155\1\156"+
    "\4\16\3\0\2\16\20\0\24\16\3\0\10\16\1\157"+
    "\14\16\3\0\2\16\20\0\2\16\1\160\21\16\3\0"+
    "\25\16\3\0\2\16\20\0\24\16\3\0\2\16\1\161"+
    "\22\16\3\0\2\16\20\0\24\16\3\0\4\16\1\162"+
    "\11\16\1\163\6\16\3\0\2\16\55\0\1\164\40\0"+
    "\1\165\2\0\24\16\3\0\25\16\3\0\2\16\20\0"+
    "\24\16\3\0\12\16\1\166\12\16\3\0\2\16\20\0"+
    "\24\16\3\0\2\16\1\167\22\16\3\0\2\16\20\0"+
    "\24\16\3\0\1\170\24\16\3\0\2\16\20\0\24\16"+
    "\3\0\12\16\1\171\12\16\3\0\2\16\20\0\24\16"+
    "\3\0\21\16\1\172\3\16\3\0\2\16\20\0\24\16"+
    "\3\0\12\16\1\173\12\16\3\0\2\16\20\0\24\16"+
    "\3\0\20\16\1\156\4\16\3\0\2\16\20\0\24\16"+
    "\3\0\24\16\1\174\3\0\2\16\20\0\24\16\3\0"+
    "\10\16\1\175\14\16\3\0\2\16\22\0\1\165\2\0"+
    "\1\165\63\0\1\176\77\0\1\132\4\0\2\124\67\0"+
    "\1\177\7\0\2\126\40\0\1\132\26\0\1\177\7\0"+
    "\2\127\40\0\1\132\36\0\2\131\67\0\1\200\2\0"+
    "\1\132\4\0\2\131\44\0\1\201\101\0\1\132\35\0"+
    "\24\16\3\0\15\16\1\202\7\16\3\0\2\16\20\0"+
    "\24\16\3\0\4\16\1\203\20\16\3\0\2\16\20\0"+
    "\24\16\3\0\1\204\24\16\3\0\2\16\20\0\7\16"+
    "\1\70\14\16\3\0\25\16\3\0\2\16\20\0\24\16"+
    "\3\0\1\205\24\16\3\0\2\16\20\0\24\16\3\0"+
    "\10\16\1\206\14\16\3\0\2\16\20\0\4\16\1\207"+
    "\17\16\3\0\25\16\3\0\2\16\20\0\24\16\3\0"+
    "\17\16\1\210\5\16\3\0\2\16\20\0\7\16\1\211"+
    "\14\16\3\0\25\16\3\0\2\16\20\0\16\16\1\212"+
    "\5\16\3\0\25\16\3\0\2\16\20\0\24\16\3\0"+
    "\12\16\1\213\12\16\3\0\2\16\20\0\7\16\1\214"+
    "\14\16\3\0\25\16\3\0\2\16\20\0\24\16\2\0"+
    "\1\215\25\16\3\0\2\16\20\0\24\16\3\0\10\16"+
    "\1\216\14\16\3\0\2\16\20\0\24\16\3\0\6\16"+
    "\1\217\16\16\3\0\2\16\20\0\14\16\1\220\7\16"+
    "\3\0\25\16\3\0\2\16\20\0\24\16\3\0\2\16"+
    "\1\221\22\16\3\0\2\16\20\0\24\16\3\0\21\16"+
    "\1\222\3\16\3\0\2\16\20\0\24\16\3\0\14\16"+
    "\1\223\10\16\3\0\2\16\20\0\4\16\1\224\17\16"+
    "\3\0\25\16\3\0\2\16\20\0\24\16\3\0\4\16"+
    "\1\225\20\16\3\0\2\16\20\0\24\16\3\0\13\16"+
    "\1\226\11\16\3\0\2\16\20\0\24\16\3\0\15\16"+
    "\1\227\7\16\3\0\2\16\71\0\1\230\27\0\24\16"+
    "\3\0\1\231\24\16\3\0\2\16\20\0\24\16\3\0"+
    "\7\16\1\232\15\16\3\0\2\16\20\0\24\16\3\0"+
    "\13\16\1\233\11\16\3\0\2\16\20\0\24\16\3\0"+
    "\15\16\1\234\7\16\3\0\2\16\20\0\24\16\3\0"+
    "\17\16\1\233\5\16\3\0\2\16\20\0\24\16\3\0"+
    "\10\16\1\235\14\16\3\0\2\16\20\0\24\16\3\0"+
    "\1\236\24\16\3\0\2\16\20\0\24\16\3\0\3\16"+
    "\1\237\21\16\3\0\2\16\10\0\1\240\146\0\1\132"+
    "\31\0\1\132\52\0\1\201\75\0\1\241\41\0\24\16"+
    "\3\0\17\16\1\242\5\16\3\0\2\16\20\0\24\16"+
    "\3\0\6\16\1\243\16\16\3\0\2\16\20\0\24\16"+
    "\3\0\2\16\1\244\22\16\3\0\2\16\20\0\24\16"+
    "\3\0\23\16\1\245\1\16\3\0\2\16\20\0\24\16"+
    "\3\0\2\16\1\246\22\16\3\0\2\16\20\0\16\16"+
    "\1\247\5\16\3\0\25\16\3\0\2\16\20\0\24\16"+
    "\3\0\1\250\24\16\3\0\2\16\20\0\11\16\1\251"+
    "\12\16\3\0\25\16\3\0\2\16\20\0\4\16\1\252"+
    "\17\16\3\0\25\16\3\0\2\16\20\0\1\251\23\16"+
    "\3\0\25\16\3\0\2\16\23\0\1\253\1\0\1\254"+
    "\73\0\24\16\3\0\4\16\1\255\20\16\3\0\2\16"+
    "\20\0\24\16\3\0\4\16\1\256\20\16\3\0\2\16"+
    "\20\0\17\16\1\257\4\16\3\0\25\16\3\0\2\16"+
    "\20\0\24\16\3\0\10\16\1\260\14\16\3\0\2\16"+
    "\20\0\24\16\3\0\17\16\1\261\5\16\3\0\2\16"+
    "\20\0\24\16\3\0\2\16\1\262\22\16\3\0\2\16"+
    "\20\0\20\16\1\263\3\16\3\0\25\16\3\0\2\16"+
    "\20\0\24\16\3\0\21\16\1\264\3\16\3\0\2\16"+
    "\20\0\24\16\3\0\16\16\1\265\6\16\3\0\2\16"+
    "\67\0\1\266\31\0\24\16\3\0\2\16\1\267\22\16"+
    "\3\0\2\16\20\0\24\16\3\0\1\270\24\16\3\0"+
    "\2\16\20\0\24\16\3\0\15\16\1\271\7\16\3\0"+
    "\2\16\20\0\24\16\3\0\6\16\1\272\16\16\3\0"+
    "\2\16\20\0\24\16\3\0\12\16\1\273\12\16\3\0"+
    "\2\16\20\0\24\16\3\0\20\16\1\113\4\16\3\0"+
    "\2\16\20\0\24\16\3\0\1\274\24\16\3\0\2\16"+
    "\10\0\1\275\110\0\24\16\3\0\10\16\1\276\14\16"+
    "\3\0\1\16\1\277\20\0\24\16\3\0\15\16\1\300"+
    "\7\16\3\0\2\16\20\0\24\16\3\0\10\16\1\301"+
    "\14\16\3\0\2\16\20\0\24\16\3\0\22\16\1\302"+
    "\2\16\3\0\2\16\20\0\24\16\3\0\22\16\1\303"+
    "\2\16\3\0\2\16\20\0\20\16\1\304\3\16\3\0"+
    "\25\16\3\0\2\16\20\0\24\16\3\0\3\16\1\305"+
    "\21\16\3\0\2\16\20\0\3\16\1\306\20\16\3\0"+
    "\25\16\3\0\2\16\27\0\1\307\71\0\1\310\100\0"+
    "\24\16\3\0\14\16\1\250\10\16\3\0\2\16\20\0"+
    "\24\16\3\0\14\16\1\311\10\16\3\0\2\16\20\0"+
    "\24\16\3\0\15\16\1\312\7\16\3\0\2\16\20\0"+
    "\24\16\3\0\4\16\1\313\20\16\3\0\2\16\20\0"+
    "\24\16\3\0\10\16\1\314\14\16\3\0\2\16\20\0"+
    "\1\315\23\16\3\0\25\16\3\0\2\16\20\0\24\16"+
    "\3\0\1\316\24\16\3\0\2\16\20\0\24\16\3\0"+
    "\15\16\1\317\7\16\3\0\2\16\70\0\1\320\30\0"+
    "\24\16\3\0\10\16\1\321\14\16\3\0\2\16\20\0"+
    "\24\16\3\0\17\16\1\322\5\16\3\0\2\16\20\0"+
    "\24\16\3\0\3\16\1\323\21\16\3\0\2\16\20\0"+
    "\24\16\3\0\1\324\24\16\3\0\2\16\20\0\24\16"+
    "\3\0\25\16\1\325\2\0\2\16\20\0\24\16\3\0"+
    "\17\16\1\326\5\16\3\0\2\16\20\0\24\16\3\0"+
    "\15\16\1\327\7\16\3\0\2\16\20\0\24\16\3\0"+
    "\14\16\1\330\10\16\3\0\2\16\20\0\24\16\3\0"+
    "\12\16\1\331\12\16\3\0\2\16\20\0\14\16\1\251"+
    "\7\16\3\0\25\16\3\0\2\16\20\0\24\16\3\0"+
    "\1\313\24\16\3\0\2\16\20\0\7\16\1\332\14\16"+
    "\3\0\25\16\3\0\2\16\25\0\1\333\75\0\1\334"+
    "\76\0\24\16\3\0\14\16\1\335\10\16\3\0\2\16"+
    "\20\0\24\16\3\0\16\16\1\336\6\16\3\0\2\16"+
    "\20\0\24\16\3\0\20\16\1\337\4\16\3\0\2\16"+
    "\64\0\1\340\34\0\24\16\3\0\25\16\3\0\1\16"+
    "\1\341\20\0\24\16\3\0\1\236\7\16\1\342\14\16"+
    "\3\0\2\16\20\0\24\16\3\0\4\16\1\271\20\16"+
    "\3\0\2\16\20\0\24\16\3\0\20\16\1\343\4\16"+
    "\3\0\2\16\47\0\1\344\51\0\24\16\3\0\10\16"+
    "\1\345\14\16\3\0\1\16\1\346\20\0\24\16\3\0"+
    "\14\16\1\313\10\16\3\0\2\16\20\0\24\16\3\0"+
    "\15\16\1\313\7\16\3\0\2\16\20\0\24\16\3\0"+
    "\21\16\1\347\3\16\3\0\2\16\20\0\4\16\1\350"+
    "\17\16\3\0\25\16\3\0\2\16\27\0\1\310\100\0"+
    "\1\351\71\0\24\16\3\0\4\16\1\352\20\16\3\0"+
    "\2\16\20\0\24\16\3\0\1\353\24\16\3\0\2\16"+
    "\4\0\1\354\13\0\24\16\3\0\25\16\3\0\2\16"+
    "\20\0\24\16\3\0\25\16\2\0\1\355\2\16\20\0"+
    "\24\16\3\0\21\16\1\174\3\16\3\0\2\16\67\0"+
    "\1\356\31\0\24\16\3\0\1\357\24\16\3\0\2\16"+
    "\20\0\24\16\3\0\25\16\1\360\2\0\2\16\20\0"+
    "\24\16\3\0\1\361\24\16\3\0\2\16\20\0\13\16"+
    "\1\362\10\16\3\0\25\16\3\0\2\16\31\0\1\363"+
    "\67\0\24\16\3\0\20\16\1\364\4\16\3\0\2\16"+
    "\20\0\24\16\3\0\12\16\1\313\12\16\3\0\2\16"+
    "\66\0\1\365\75\0\1\366\35\0\24\16\3\0\20\16"+
    "\1\367\4\16\3\0\2\16\47\0\1\370\51\0\24\16"+
    "\3\0\3\16\1\371\21\16\3\0\2\16\20\0\20\16"+
    "\1\372\3\16\3\0\25\16\3\0\2\16\53\0\1\373"+
    "\114\0\1\374\31\0\4\16\1\375\17\16\3\0\25\16"+
    "\3\0\2\16\61\0\1\376\37\0\17\16\1\377\4\16"+
    "\3\0\25\16\3\0\2\16\47\0\1\u0100\102\0\1\u0101"+
    "\106\0\1\u0102\105\0\1\u0103\77\0\1\u0104\64\0\1\u0105"+
    "\103\0\1\u0106\75\0\1\u0107\120\0\1\u0108\11\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[14690];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\4\1\2\11\1\1\2\11"+
    "\14\1\2\11\14\1\1\0\1\11\1\1\4\0\1\1"+
    "\1\0\25\1\1\0\13\1\1\0\1\1\1\0\3\1"+
    "\2\0\1\11\31\1\1\0\1\11\11\1\2\0\14\1"+
    "\1\0\12\1\1\0\10\1\1\0\11\1\2\0\11\1"+
    "\1\0\6\1\1\11\11\1\2\0\7\1\1\0\4\1"+
    "\1\0\5\1\2\0\3\1\1\11\3\1\1\0\4\1"+
    "\1\0\2\1\2\0\1\11\1\1\1\0\2\1\1\11"+
    "\1\1\1\0\1\11\1\1\1\0\2\1\1\0\1\11"+
    "\1\1\1\0\1\1\10\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[264];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }
    
    // debug (puedes comentar el println cuando no lo necesites)
    private void debugToken(int type, Object val) {
        System.err.println("TOKEN: " + sym.terminalNames[type] +
        (val != null ? (" -> " + val) : ""));
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new Error("Caracter ilegal <" + yytext() + "> en línea " + (yyline+1) + ", columna " + (yycolumn+1));
            }
          // fall through
          case 35: break;
          case 2:
            { /* ignorar */
            }
          // fall through
          case 36: break;
          case 3:
            { debugToken(sym.NUEVA_LINEA, null); return symbol(sym.NUEVA_LINEA);
            }
          // fall through
          case 37: break;
          case 4:
            { debugToken(sym.PRECIO, null); return symbol(sym.PRECIO, yytext());
            }
          // fall through
          case 38: break;
          case 5:
            { debugToken(sym.ESTRELLAS, null); return symbol(sym.ESTRELLAS, yytext());
            }
          // fall through
          case 39: break;
          case 6:
            { debugToken(sym.COMA, null); return symbol(sym.COMA);
            }
          // fall through
          case 40: break;
          case 7:
            { debugToken(sym.PUNTO, null); return symbol(sym.PUNTO);
            }
          // fall through
          case 41: break;
          case 8:
            { debugToken(sym.ENTERO, null); return symbol(sym.ENTERO, Integer.parseInt(yytext()));
            }
          // fall through
          case 42: break;
          case 9:
            { debugToken(sym.COLON, null); return symbol(sym.COLON);
            }
          // fall through
          case 43: break;
          case 10:
            { debugToken(sym.EQUALS, null); return symbol(sym.EQUALS);
            }
          // fall through
          case 44: break;
          case 11:
            { debugToken(sym.PALABRA, yytext()); return symbol(sym.PALABRA, yytext());
            }
          // fall through
          case 45: break;
          case 12:
            { debugToken(sym.UNIDAD, null); return symbol(sym.UNIDAD, yytext());
            }
          // fall through
          case 46: break;
          case 13:
            { debugToken(sym.LBRACKET, null); return symbol(sym.LBRACKET);
            }
          // fall through
          case 47: break;
          case 14:
            { debugToken(sym.RBRACKET, null); return symbol(sym.RBRACKET);
            }
          // fall through
          case 48: break;
          case 15:
            { String txt = yytext();
        return symbol(sym.TEXTO_COMILLAS, txt.substring(1, txt.length()-1));
            }
          // fall through
          case 49: break;
          case 16:
            { debugToken(sym.TIEMPO_VAL, null); return symbol(sym.TIEMPO_VAL, yytext());
            }
          // fall through
          case 50: break;
          case 17:
            { debugToken(sym.DECIMAL, null); return symbol(sym.DECIMAL, yytext());
            }
          // fall through
          case 51: break;
          case 18:
            { debugToken(sym.FRACCION, null); return symbol(sym.FRACCION, yytext());
            }
          // fall through
          case 52: break;
          case 19:
            { debugToken(sym.OBS, null); return symbol(sym.OBS);
            }
          // fall through
          case 53: break;
          case 20:
            { debugToken(sym.KCAL, null); return symbol(sym.KCAL);
            }
          // fall through
          case 54: break;
          case 21:
            { debugToken(sym.TIPO, null); return symbol(sym.TIPO);
            }
          // fall through
          case 55: break;
          case 22:
            { debugToken(sym.NIVEL_TEXTO, null); return symbol(sym.NIVEL_TEXTO, yytext());
            }
          // fall through
          case 56: break;
          case 23:
            { debugToken(sym.PASOS, null); return symbol(sym.PASOS);
            }
          // fall through
          case 57: break;
          case 24:
            { debugToken(sym.ORIGEN, null); return symbol(sym.ORIGEN);
            }
          // fall through
          case 58: break;
          case 25:
            { debugToken(sym.CATEGORIA, null); return symbol(sym.CATEGORIA, yytext());
            }
          // fall through
          case 59: break;
          case 26:
            { debugToken(sym.RECETA, null); return symbol(sym.RECETA);
            }
          // fall through
          case 60: break;
          case 27:
            { debugToken(sym.TIEMPO_KW, null); return symbol(sym.TIEMPO_KW);
            }
          // fall through
          case 61: break;
          case 28:
            { debugToken(sym.UNIDAD_LIBRE, null); return symbol(sym.UNIDAD_LIBRE, yytext());
            }
          // fall through
          case 62: break;
          case 29:
            { debugToken(sym.CALORIAS, null); return symbol(sym.CALORIAS);
            }
          // fall through
          case 63: break;
          case 30:
            { debugToken(sym.PORCIONES, null); return symbol(sym.PORCIONES);
            }
          // fall through
          case 64: break;
          case 31:
            { debugToken(sym.CATEGORIAS, null); return symbol(sym.CATEGORIAS);
            }
          // fall through
          case 65: break;
          case 32:
            { debugToken(sym.DIFICULTAD, null); return symbol(sym.DIFICULTAD);
            }
          // fall through
          case 66: break;
          case 33:
            { debugToken(sym.INGREDIENTES, null); return symbol(sym.INGREDIENTES);
            }
          // fall through
          case 67: break;
          case 34:
            { debugToken(sym.RECETAS_RELACIONADAS, null); return symbol(sym.RECETAS_RELACIONADAS);
            }
          // fall through
          case 68: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
