// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: sandwich.flex

/* ---- sandwich.flex ---- */
import java_cup.runtime.Symbol;


@SuppressWarnings("fallthrough")
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int S_VAL = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u1100\1\u1200\1\u1300\1\u1400\1\u1100\1\u1500\1\u1600"+
    "\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u1c00\1\u1100\1\u1d00"+
    "\1\u1e00\1\u1f00\12\u2000\1\u2100\1\u2200\1\u2300\1\u2000\1\u2400"+
    "\1\u2500\2\u2000\31\u1100\1\u2600\121\u1100\1\u2700\4\u1100\1\u2800"+
    "\1\u1100\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\1\u2e00\53\u1100"+
    "\1\u2f00\10\u3000\31\u2000\1\u1100\1\u3100\1\u3200\1\u1100\1\u3300"+
    "\1\u3400\1\u3500\1\u3600\1\u2000\1\u3700\1\u3800\1\u3900\1\u3a00"+
    "\1\u1100\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000\1\u4100"+
    "\1\u2000\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800"+
    "\1\u4900\1\u4a00\1\u4b00\1\u4c00\1\u4d00\1\u2000\1\u4e00\1\u4f00"+
    "\1\u5000\1\u2000\3\u1100\1\u5100\1\u5200\1\u5300\12\u2000\4\u1100"+
    "\1\u5400\17\u2000\2\u1100\1\u5500\41\u2000\2\u1100\1\u5600\1\u5700"+
    "\2\u2000\1\u5800\1\u5900\27\u1100\1\u5a00\2\u1100\1\u5b00\45\u2000"+
    "\1\u1100\1\u5c00\1\u5d00\11\u2000\1\u5e00\27\u2000\1\u5f00\1\u6000"+
    "\1\u6100\1\u6200\11\u2000\1\u6300\1\u6400\5\u2000\1\u6500\1\u6600"+
    "\4\u2000\1\u6700\21\u2000\246\u1100\1\u6800\20\u1100\1\u6900\1\u6a00"+
    "\25\u1100\1\u6b00\34\u1100\1\u6c00\14\u2000\2\u1100\1\u6d00\u0e05\u2000";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\0\1\6\4\0\1\7\4\0\1\10\1\7\1\11"+
    "\1\12\12\13\1\14\6\0\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\26\1\35\1\36\1\37"+
    "\1\40\4\26\1\41\1\42\1\43\1\44\3\0\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\26"+
    "\1\35\1\36\1\37\1\40\4\26\1\41\12\0\1\3"+
    "\44\0\1\26\12\0\1\26\4\0\1\26\5\0\15\26"+
    "\1\45\11\26\1\0\25\26\1\45\11\26\1\0\70\26"+
    "\2\25\115\26\1\36\u0142\26\4\0\14\26\16\0\5\26"+
    "\7\0\1\26\1\0\1\26\126\0\1\26\52\0\5\26"+
    "\1\0\2\26\2\0\4\26\1\0\1\26\6\0\1\26"+
    "\1\0\3\26\1\0\1\26\1\0\24\26\1\0\123\26"+
    "\1\0\213\26\10\0\246\26\1\0\46\26\2\0\1\26"+
    "\6\0\51\26\107\0\33\26\4\0\4\26\55\0\53\26"+
    "\43\0\2\26\1\0\143\26\1\0\1\26\17\0\2\26"+
    "\7\0\2\26\12\0\3\26\2\0\1\26\20\0\1\26"+
    "\1\0\36\26\35\0\131\26\13\0\1\26\30\0\41\26"+
    "\11\0\2\26\4\0\1\26\5\0\26\26\4\0\1\26"+
    "\11\0\1\26\3\0\1\26\27\0\31\26\7\0\13\26"+
    "\65\0\25\26\1\0\10\26\106\0\66\26\3\0\1\26"+
    "\22\0\1\26\7\0\12\26\17\0\20\26\4\0\10\26"+
    "\2\0\2\26\2\0\26\26\1\0\7\26\1\0\1\26"+
    "\3\0\4\26\3\0\1\26\20\0\1\26\15\0\2\26"+
    "\1\0\3\26\16\0\2\26\12\0\1\26\10\0\6\26"+
    "\4\0\2\26\2\0\26\26\1\0\7\26\1\0\2\26"+
    "\1\0\2\26\1\0\2\26\37\0\4\26\1\0\1\26"+
    "\23\0\3\26\20\0\11\26\1\0\3\26\1\0\26\26"+
    "\1\0\7\26\1\0\2\26\1\0\5\26\3\0\1\26"+
    "\22\0\1\26\17\0\2\26\27\0\1\26\13\0\10\26"+
    "\2\0\2\26\2\0\26\26\1\0\7\26\1\0\2\26"+
    "\1\0\5\26\3\0\1\26\36\0\2\26\1\0\3\26"+
    "\17\0\1\26\21\0\1\26\1\0\6\26\3\0\3\26"+
    "\1\0\4\26\3\0\2\26\1\0\1\26\1\0\2\26"+
    "\3\0\2\26\3\0\3\26\3\0\14\26\26\0\1\26"+
    "\64\0\10\26\1\0\3\26\1\0\27\26\1\0\20\26"+
    "\3\0\1\26\32\0\3\26\5\0\2\26\36\0\1\26"+
    "\4\0\10\26\1\0\3\26\1\0\27\26\1\0\12\26"+
    "\1\0\5\26\3\0\1\26\40\0\1\26\1\0\2\26"+
    "\17\0\2\26\22\0\10\26\1\0\3\26\1\0\51\26"+
    "\2\0\1\26\20\0\1\26\5\0\3\26\10\0\3\26"+
    "\30\0\6\26\5\0\22\26\3\0\30\26\1\0\11\26"+
    "\1\0\1\26\2\0\7\26\72\0\60\26\1\0\2\26"+
    "\14\0\7\26\72\0\2\26\1\0\1\26\1\0\5\26"+
    "\1\0\30\26\1\0\1\26\1\0\12\26\1\0\2\26"+
    "\11\0\1\26\2\0\5\26\1\0\1\26\25\0\4\26"+
    "\40\0\1\26\77\0\10\26\1\0\44\26\33\0\5\26"+
    "\163\0\53\26\24\0\1\26\20\0\6\26\4\0\4\26"+
    "\3\0\1\26\3\0\2\26\7\0\3\26\4\0\15\26"+
    "\14\0\1\26\21\0\46\26\1\0\1\26\5\0\1\26"+
    "\2\0\53\26\1\0\u014d\26\1\0\4\26\2\0\7\26"+
    "\1\0\1\26\1\0\4\26\2\0\51\26\1\0\4\26"+
    "\2\0\41\26\1\0\4\26\2\0\7\26\1\0\1\26"+
    "\1\0\4\26\2\0\17\26\1\0\71\26\1\0\4\26"+
    "\2\0\103\26\45\0\20\26\20\0\126\26\2\0\6\26"+
    "\3\0\u016c\26\2\0\21\26\1\0\32\26\5\0\113\26"+
    "\6\0\10\26\7\0\15\26\1\0\4\26\16\0\22\26"+
    "\16\0\22\26\16\0\15\26\1\0\3\26\17\0\64\26"+
    "\43\0\1\26\4\0\1\26\103\0\131\26\7\0\5\26"+
    "\2\0\42\26\1\0\1\26\5\0\106\26\12\0\37\26"+
    "\61\0\36\26\2\0\5\26\13\0\54\26\4\0\32\26"+
    "\66\0\27\26\11\0\65\26\122\0\1\26\135\0\57\26"+
    "\21\0\7\26\67\0\36\26\15\0\2\26\12\0\54\26"+
    "\32\0\44\26\51\0\3\26\12\0\44\26\2\0\11\26"+
    "\7\0\53\26\2\0\3\26\51\0\4\26\1\0\6\26"+
    "\1\0\2\26\3\0\1\26\5\0\300\26\100\0\26\26"+
    "\2\0\6\26\2\0\46\26\2\0\6\26\2\0\10\26"+
    "\1\0\1\26\1\0\1\26\1\0\1\26\1\0\37\26"+
    "\2\0\65\26\1\0\7\26\1\0\1\26\3\0\3\26"+
    "\1\0\7\26\3\0\4\26\2\0\6\26\4\0\15\26"+
    "\5\0\3\26\1\0\7\26\53\0\2\3\107\0\1\26"+
    "\15\0\1\26\20\0\15\26\145\0\1\26\4\0\1\26"+
    "\2\0\12\26\1\0\1\26\3\0\5\26\6\0\1\26"+
    "\1\0\1\26\1\0\1\26\1\0\1\27\3\26\1\0"+
    "\13\26\2\0\4\26\5\0\5\26\4\0\1\26\64\0"+
    "\2\26\u017b\0\57\26\1\0\57\26\1\0\205\26\6\0"+
    "\4\26\3\0\2\26\14\0\46\26\1\0\1\26\5\0"+
    "\1\26\2\0\70\26\7\0\1\26\20\0\27\26\11\0"+
    "\7\26\1\0\7\26\1\0\7\26\1\0\7\26\1\0"+
    "\7\26\1\0\7\26\1\0\7\26\1\0\7\26\120\0"+
    "\1\26\325\0\2\26\52\0\5\26\5\0\2\26\4\0"+
    "\126\26\6\0\3\26\1\0\132\26\1\0\4\26\5\0"+
    "\53\26\1\0\136\26\21\0\33\26\65\0\306\26\112\0"+
    "\360\26\20\0\215\26\103\0\56\26\2\0\15\26\3\0"+
    "\20\26\12\0\2\26\24\0\57\26\20\0\37\26\2\0"+
    "\106\26\61\0\11\26\2\0\147\26\2\0\65\26\2\0"+
    "\5\26\60\0\13\26\1\0\3\26\1\0\4\26\1\0"+
    "\27\26\35\0\64\26\16\0\62\26\76\0\6\26\3\0"+
    "\1\26\1\0\2\26\13\0\34\26\12\0\27\26\31\0"+
    "\35\26\7\0\57\26\34\0\1\26\20\0\5\26\1\0"+
    "\12\26\12\0\5\26\1\0\51\26\27\0\3\26\1\0"+
    "\10\26\24\0\27\26\3\0\1\26\3\0\62\26\1\0"+
    "\1\26\3\0\2\26\2\0\5\26\2\0\1\26\1\0"+
    "\1\26\30\0\3\26\2\0\13\26\7\0\3\26\14\0"+
    "\6\26\2\0\6\26\2\0\6\26\11\0\7\26\1\0"+
    "\7\26\1\0\53\26\1\0\14\26\10\0\163\26\35\0"+
    "\244\26\14\0\27\26\4\0\61\26\4\0\u0100\3\156\26"+
    "\2\0\152\26\46\0\7\26\14\0\5\26\5\0\1\26"+
    "\1\0\12\26\1\0\15\26\1\0\5\26\1\0\1\26"+
    "\1\0\2\26\1\0\2\26\1\0\154\26\41\0\153\26"+
    "\22\0\100\26\2\0\66\26\50\0\14\26\164\0\5\26"+
    "\1\0\207\26\2\0\1\46\41\0\32\26\6\0\32\26"+
    "\13\0\131\26\3\0\6\26\2\0\6\26\2\0\6\26"+
    "\2\0\3\26\43\0\14\26\1\0\32\26\1\0\23\26"+
    "\1\0\2\26\1\0\17\26\2\0\16\26\42\0\173\26"+
    "\205\0\35\26\3\0\61\26\57\0\40\26\15\0\24\26"+
    "\1\0\10\26\6\0\46\26\12\0\36\26\2\0\44\26"+
    "\4\0\10\26\60\0\236\26\22\0\44\26\4\0\44\26"+
    "\4\0\50\26\10\0\64\26\234\0\67\26\11\0\26\26"+
    "\12\0\10\26\230\0\6\26\2\0\1\26\1\0\54\26"+
    "\1\0\2\26\3\0\1\26\2\0\27\26\12\0\27\26"+
    "\11\0\37\26\101\0\23\26\1\0\2\26\12\0\26\26"+
    "\12\0\32\26\106\0\70\26\6\0\2\26\100\0\1\26"+
    "\17\0\4\26\1\0\3\26\1\0\35\26\52\0\35\26"+
    "\3\0\35\26\43\0\10\26\1\0\34\26\33\0\66\26"+
    "\12\0\26\26\12\0\23\26\15\0\22\26\156\0\111\26"+
    "\67\0\63\26\15\0\63\26\15\0\44\26\334\0\35\26"+
    "\12\0\1\26\10\0\26\26\232\0\27\26\14\0\65\26"+
    "\113\0\55\26\40\0\31\26\32\0\44\26\35\0\1\26"+
    "\13\0\43\26\3\0\1\26\14\0\60\26\16\0\4\26"+
    "\25\0\1\26\1\0\1\26\43\0\22\26\1\0\31\26"+
    "\124\0\7\26\1\0\1\26\1\0\4\26\1\0\17\26"+
    "\1\0\12\26\7\0\57\26\46\0\10\26\2\0\2\26"+
    "\2\0\26\26\1\0\7\26\1\0\2\26\1\0\5\26"+
    "\3\0\1\26\22\0\1\26\14\0\5\26\236\0\65\26"+
    "\22\0\4\26\24\0\1\26\40\0\60\26\24\0\2\26"+
    "\1\0\1\26\270\0\57\26\51\0\4\26\44\0\60\26"+
    "\24\0\1\26\73\0\53\26\15\0\1\26\107\0\33\26"+
    "\345\0\54\26\164\0\100\26\37\0\1\26\240\0\10\26"+
    "\2\0\47\26\20\0\1\26\1\0\1\26\34\0\1\26"+
    "\12\0\50\26\7\0\1\26\25\0\1\26\13\0\56\26"+
    "\23\0\1\26\42\0\71\26\7\0\11\26\1\0\45\26"+
    "\21\0\1\26\61\0\36\26\160\0\7\26\1\0\2\26"+
    "\1\0\46\26\25\0\1\26\31\0\6\26\1\0\2\26"+
    "\1\0\40\26\16\0\1\26\u0147\0\23\26\15\0\232\26"+
    "\346\0\304\26\274\0\57\26\321\0\107\26\271\0\71\26"+
    "\7\0\37\26\161\0\36\26\22\0\60\26\20\0\4\26"+
    "\37\0\25\26\5\0\23\26\260\0\100\26\200\0\113\26"+
    "\5\0\1\26\102\0\15\26\100\0\2\26\1\0\1\26"+
    "\34\0\370\26\10\0\363\26\15\0\37\26\61\0\3\26"+
    "\21\0\4\26\10\0\u018c\26\4\0\153\26\5\0\15\26"+
    "\3\0\11\26\7\0\12\26\146\0\125\26\1\0\107\26"+
    "\1\0\2\26\2\0\1\26\2\0\2\26\2\0\4\26"+
    "\1\0\14\26\1\0\1\26\1\0\7\26\1\0\101\26"+
    "\1\0\4\26\2\0\10\26\1\0\7\26\1\0\34\26"+
    "\1\0\4\26\1\0\5\26\1\0\1\26\3\0\7\26"+
    "\1\0\u0154\26\2\0\31\26\1\0\31\26\1\0\37\26"+
    "\1\0\31\26\1\0\37\26\1\0\31\26\1\0\37\26"+
    "\1\0\31\26\1\0\37\26\1\0\31\26\1\0\10\26"+
    "\64\0\55\26\12\0\7\26\20\0\1\26\u0171\0\54\26"+
    "\24\0\305\26\73\0\104\26\7\0\1\26\264\0\4\26"+
    "\1\0\33\26\1\0\2\26\1\0\1\26\2\0\1\26"+
    "\1\0\12\26\1\0\4\26\1\0\1\26\1\0\1\26"+
    "\6\0\1\26\4\0\1\26\1\0\1\26\1\0\1\26"+
    "\1\0\3\26\1\0\2\26\1\0\1\26\2\0\1\26"+
    "\1\0\1\26\1\0\1\26\1\0\1\26\1\0\1\26"+
    "\1\0\2\26\1\0\1\26\2\0\4\26\1\0\7\26"+
    "\1\0\4\26\1\0\4\26\1\0\1\26\1\0\12\26"+
    "\1\0\21\26\5\0\3\26\1\0\5\26\1\0\21\26"+
    "\104\0\327\26\51\0\65\26\13\0\336\26\2\0\u0182\26"+
    "\16\0\u0131\26\37\0\36\26\342\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[28160];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\2\3\1\1\1\4\1\5\1\6"+
    "\4\7\1\10\7\7\1\11\1\12\1\2\1\13\2\14"+
    "\1\2\1\0\1\15\2\0\1\16\1\0\14\7\1\5"+
    "\1\0\5\7\1\17\7\7\1\0\5\7\1\0\1\17"+
    "\6\7\1\0\6\7\1\20\3\7\1\0\1\21\1\0"+
    "\11\7\1\22\6\7\1\0\1\23\1\7\1\24\1\7"+
    "\1\0\1\25\5\7\2\0\1\26\4\7\1\0\3\7"+
    "\1\0\1\27\2\0\1\30\1\0\1\31\1\7\1\0"+
    "\1\32\10\0\1\33\1\0\1\33";

  private static int [] zzUnpackAction() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\47\0\116\0\165\0\116\0\234\0\303\0\116"+
    "\0\352\0\116\0\u0111\0\u0138\0\u015f\0\u0186\0\u0138\0\u01ad"+
    "\0\u01d4\0\u01fb\0\u0222\0\u0249\0\u0270\0\u0297\0\116\0\116"+
    "\0\116\0\u02be\0\116\0\u02e5\0\u02be\0\303\0\116\0\u030c"+
    "\0\u0333\0\u0333\0\u035a\0\u0381\0\u03a8\0\u03cf\0\u03f6\0\u041d"+
    "\0\u0444\0\u046b\0\u0492\0\u04b9\0\u04e0\0\u0507\0\u052e\0\u0333"+
    "\0\u0555\0\u057c\0\u05a3\0\u05ca\0\u05f1\0\u0618\0\u063f\0\u0666"+
    "\0\u068d\0\u06b4\0\u06db\0\u0702\0\u0729\0\u0750\0\u0777\0\u079e"+
    "\0\u07c5\0\u07ec\0\u0813\0\u083a\0\u0861\0\116\0\u0888\0\u08af"+
    "\0\u08d6\0\u08fd\0\u0924\0\u094b\0\u0972\0\u0999\0\u09c0\0\u09e7"+
    "\0\u0a0e\0\u0a35\0\u0a5c\0\u0138\0\u0a83\0\u0aaa\0\u0ad1\0\u0af8"+
    "\0\116\0\u0b1f\0\u0b46\0\u0b6d\0\u0b94\0\u0bbb\0\u0be2\0\u0c09"+
    "\0\u0c30\0\u0c57\0\u0c7e\0\116\0\u0ca5\0\u0ccc\0\u0cf3\0\u0d1a"+
    "\0\u0d41\0\u0d68\0\u0d8f\0\116\0\u0db6\0\u0ddd\0\u0e04\0\u0e2b"+
    "\0\116\0\u0e52\0\u0e79\0\u0ea0\0\u0ec7\0\u0eee\0\u0f15\0\u0f3c"+
    "\0\116\0\u0f63\0\u0f8a\0\u0fb1\0\u0fd8\0\u0fff\0\u1026\0\u104d"+
    "\0\u1074\0\u109b\0\116\0\u10c2\0\u10e9\0\116\0\u1110\0\116"+
    "\0\u1137\0\u115e\0\u0138\0\u1185\0\u11ac\0\u11d3\0\u11fa\0\u1221"+
    "\0\u1248\0\u126f\0\u1296\0\u12bd\0\u12bd\0\116";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\0\1\4\1\6\1\7\1\3"+
    "\1\10\2\3\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\2\14\2\17\1\20\1\14\1\21\1\17\1\22\1\14"+
    "\1\23\1\24\1\25\1\14\1\26\1\17\1\14\1\27"+
    "\1\3\1\30\1\14\1\31\2\32\1\33\2\32\1\34"+
    "\40\32\1\35\50\0\1\4\2\0\1\4\44\0\1\5"+
    "\44\0\6\36\1\37\34\36\1\40\3\36\10\0\1\41"+
    "\1\42\1\41\1\11\34\0\1\43\2\0\1\43\2\0"+
    "\1\14\5\0\25\14\3\0\1\14\10\0\1\14\5\0"+
    "\25\14\3\0\1\14\10\0\1\14\5\0\1\44\22\14"+
    "\1\45\1\14\3\0\1\14\10\0\1\14\5\0\10\14"+
    "\1\46\14\14\3\0\1\14\10\0\1\14\5\0\15\14"+
    "\1\47\7\14\3\0\1\14\10\0\1\14\5\0\6\14"+
    "\1\17\16\14\3\0\1\14\10\0\1\14\5\0\10\14"+
    "\1\50\14\14\3\0\1\14\10\0\1\14\5\0\1\14"+
    "\1\51\16\14\1\52\4\14\3\0\1\14\10\0\1\14"+
    "\5\0\1\53\15\14\1\54\6\14\3\0\1\14\10\0"+
    "\1\14\5\0\4\14\1\55\20\14\3\0\1\14\10\0"+
    "\1\14\5\0\1\56\7\14\1\57\14\14\3\0\1\14"+
    "\1\0\2\32\1\0\2\32\1\0\41\32\2\0\1\33"+
    "\44\0\2\36\4\0\41\36\13\0\1\60\34\0\1\43"+
    "\2\0\1\43\16\0\1\61\32\0\1\14\5\0\13\14"+
    "\1\62\6\14\1\63\2\14\3\0\1\14\10\0\1\14"+
    "\5\0\2\14\1\64\22\14\3\0\1\14\10\0\1\14"+
    "\5\0\5\14\1\65\17\14\3\0\1\14\10\0\1\14"+
    "\5\0\6\14\1\66\16\14\3\0\1\14\10\0\1\14"+
    "\5\0\15\14\1\17\7\14\3\0\1\14\10\0\1\14"+
    "\5\0\21\14\1\67\3\14\3\0\1\14\10\0\1\14"+
    "\5\0\10\14\1\70\14\14\3\0\1\14\10\0\1\14"+
    "\5\0\21\14\1\71\3\14\3\0\1\14\10\0\1\14"+
    "\5\0\20\14\1\72\4\14\3\0\1\14\10\0\1\14"+
    "\5\0\2\14\1\73\22\14\3\0\1\14\10\0\1\14"+
    "\5\0\24\14\1\74\3\0\1\14\10\0\1\14\5\0"+
    "\4\14\1\75\12\14\1\76\5\14\3\0\1\14\41\0"+
    "\1\77\15\0\1\14\5\0\16\14\1\100\6\14\3\0"+
    "\1\14\10\0\1\14\5\0\4\14\1\101\20\14\3\0"+
    "\1\14\10\0\1\14\5\0\7\14\1\102\15\14\3\0"+
    "\1\14\10\0\1\14\5\0\10\14\1\103\14\14\3\0"+
    "\1\14\10\0\1\14\5\0\20\14\1\104\4\14\3\0"+
    "\1\14\2\0\1\105\2\0\1\105\2\0\1\14\4\0"+
    "\1\106\25\14\3\0\1\14\10\0\1\14\5\0\6\14"+
    "\1\107\16\14\3\0\1\14\10\0\1\14\5\0\16\14"+
    "\1\110\6\14\3\0\1\14\10\0\1\14\5\0\2\14"+
    "\1\111\22\14\3\0\1\14\10\0\1\14\5\0\4\14"+
    "\1\112\20\14\3\0\1\14\10\0\1\14\5\0\1\17"+
    "\24\14\3\0\1\14\10\0\1\14\5\0\14\14\1\113"+
    "\10\14\3\0\1\14\10\0\1\14\5\0\16\14\1\114"+
    "\6\14\3\0\1\14\37\0\1\115\17\0\1\14\5\0"+
    "\20\14\1\116\4\14\3\0\1\14\10\0\1\14\5\0"+
    "\6\14\1\117\16\14\3\0\1\14\10\0\1\14\5\0"+
    "\1\120\24\14\3\0\1\14\10\0\1\14\5\0\2\14"+
    "\1\121\22\14\3\0\1\14\10\0\1\14\5\0\4\14"+
    "\1\122\20\14\3\0\1\14\2\0\1\105\2\0\1\105"+
    "\7\0\1\106\41\0\1\14\5\0\4\14\1\123\20\14"+
    "\3\0\1\14\10\0\1\14\5\0\21\14\1\124\3\14"+
    "\3\0\1\14\10\0\1\14\5\0\10\14\1\125\14\14"+
    "\3\0\1\14\10\0\1\14\5\0\22\14\1\126\2\14"+
    "\3\0\1\14\10\0\1\14\5\0\17\14\1\127\5\14"+
    "\3\0\1\14\2\0\1\130\2\0\1\130\2\0\1\14"+
    "\4\0\1\131\25\14\3\0\1\14\40\0\1\132\16\0"+
    "\1\14\5\0\25\14\3\0\1\133\10\0\1\14\5\0"+
    "\16\14\1\134\6\14\3\0\1\14\10\0\1\14\5\0"+
    "\20\14\1\135\4\14\3\0\1\14\10\0\1\14\5\0"+
    "\23\14\1\136\1\14\3\0\1\14\10\0\1\14\5\0"+
    "\3\14\1\137\21\14\3\0\1\14\10\0\1\14\5\0"+
    "\15\14\1\140\7\14\3\0\1\14\10\0\1\14\5\0"+
    "\16\14\1\141\6\14\3\0\1\14\10\0\1\14\5\0"+
    "\1\142\24\14\3\0\1\14\10\0\1\14\5\0\16\14"+
    "\1\143\6\14\3\0\1\14\2\0\1\130\2\0\1\130"+
    "\7\0\1\131\65\0\1\144\22\0\1\14\5\0\1\145"+
    "\24\14\3\0\1\14\10\0\1\14\5\0\20\14\1\146"+
    "\4\14\3\0\1\14\10\0\1\14\5\0\1\147\7\14"+
    "\1\150\14\14\3\0\1\14\10\0\1\14\5\0\13\14"+
    "\1\151\11\14\3\0\1\14\10\0\1\14\5\0\10\14"+
    "\1\152\14\14\3\0\1\14\2\0\1\153\2\0\1\153"+
    "\2\0\1\14\4\0\1\154\25\14\3\0\1\14\10\0"+
    "\1\14\5\0\15\14\1\155\7\14\3\0\1\14\2\0"+
    "\1\156\2\0\1\156\2\0\1\14\5\0\21\14\1\157"+
    "\3\14\3\0\1\14\2\0\1\160\2\0\1\160\2\0"+
    "\1\14\4\0\1\161\25\14\3\0\1\14\10\0\1\14"+
    "\5\0\21\14\1\162\3\14\3\0\1\14\10\0\1\14"+
    "\5\0\25\14\3\0\1\163\10\0\1\14\5\0\21\14"+
    "\1\17\3\14\3\0\1\14\10\0\1\14\5\0\22\14"+
    "\1\74\2\14\3\0\1\14\10\0\1\14\5\0\22\14"+
    "\1\164\2\14\3\0\1\14\10\0\1\14\5\0\4\14"+
    "\1\165\20\14\3\0\1\14\2\0\1\153\2\0\1\153"+
    "\7\0\1\154\41\0\1\14\5\0\4\14\1\166\20\14"+
    "\3\0\1\14\2\0\1\156\2\0\1\156\43\0\1\167"+
    "\2\0\1\167\2\0\1\14\5\0\25\14\3\0\1\14"+
    "\2\0\1\160\2\0\1\160\7\0\1\161\33\0\1\170"+
    "\2\0\1\170\2\0\1\14\4\0\1\171\25\14\3\0"+
    "\1\14\10\0\1\14\5\0\1\172\24\14\3\0\1\14"+
    "\10\0\1\14\5\0\1\173\24\14\3\0\1\14\10\0"+
    "\1\14\5\0\15\14\1\174\7\14\3\0\1\14\10\0"+
    "\1\14\5\0\21\14\1\175\3\14\3\0\1\14\2\0"+
    "\1\167\2\0\1\167\30\0\1\176\12\0\1\170\2\0"+
    "\1\170\7\0\1\171\41\0\1\14\5\0\21\14\1\177"+
    "\3\14\3\0\1\14\10\0\1\14\5\0\3\14\1\200"+
    "\21\14\3\0\1\14\10\0\1\14\5\0\22\14\1\201"+
    "\2\14\3\0\1\14\2\0\1\202\2\0\1\202\2\0"+
    "\1\14\4\0\1\203\25\14\3\0\1\14\22\0\1\204"+
    "\26\0\1\205\2\0\1\205\2\0\1\14\4\0\1\206"+
    "\25\14\3\0\1\14\2\0\1\207\2\0\1\207\2\0"+
    "\1\14\4\0\1\210\25\14\3\0\1\14\10\0\1\14"+
    "\5\0\4\14\1\211\20\14\3\0\1\14\2\0\1\202"+
    "\2\0\1\202\7\0\1\203\62\0\1\212\17\0\1\205"+
    "\2\0\1\205\7\0\1\206\33\0\1\207\2\0\1\207"+
    "\7\0\1\210\41\0\1\14\5\0\21\14\1\213\3\14"+
    "\3\0\1\14\16\0\1\214\50\0\1\215\54\0\1\216"+
    "\54\0\1\217\45\0\1\220\31\0\1\221\51\0\1\222"+
    "\43\0\1\223\67\0\1\224\11\0\1\225\2\0\1\225"+
    "\7\0\1\226\32\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[4836];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\2\1\1\11\1\1\1\11"+
    "\14\1\3\11\1\1\1\11\2\1\1\0\1\11\2\0"+
    "\1\1\1\0\15\1\1\0\15\1\1\0\5\1\1\0"+
    "\1\11\6\1\1\0\12\1\1\0\1\11\1\0\11\1"+
    "\1\11\6\1\1\0\1\11\3\1\1\0\1\11\5\1"+
    "\2\0\1\11\4\1\1\0\3\1\1\0\1\11\2\0"+
    "\1\11\1\0\1\11\1\1\1\0\1\1\10\0\1\1"+
    "\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
  private Symbol symbol(int type) { return new Symbol(type, yyline, yycolumn); }
  private Symbol symbol(int type, Object val) { return new Symbol(type, yyline, yycolumn, val); }

  // debug (puedes comentar el println cuando no lo necesites)
  private void debugToken(int type, Object val) {
    System.err.println("TOKEN: " + sym.terminalNames[type] +
      (val != null ? (" -> " + val) : ""));
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case S_VAL: {
              debugToken(sym.NL, null);
  yybegin(YYINITIAL);
  return symbol(sym.NL);
            }  // fall though
            case 151: break;
            default:
              {
                return symbol(sym.EOF);
              }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new Error("Carácter ilegal: " + yytext());
            }
          // fall through
          case 28: break;
          case 2:
            { /* skip */
            }
          // fall through
          case 29: break;
          case 3:
            { debugToken(sym.NL, null); return symbol(sym.NL);
            }
          // fall through
          case 30: break;
          case 4:
            { return symbol(sym.COMA);
            }
          // fall through
          case 31: break;
          case 5:
            { debugToken(sym.CANTIDAD, yytext()); return symbol(sym.CANTIDAD, yytext());
            }
          // fall through
          case 32: break;
          case 6:
            { return symbol(sym.DOSP);
            }
          // fall through
          case 33: break;
          case 7:
            { debugToken(sym.WORD, yytext()); return symbol(sym.WORD, yytext());
            }
          // fall through
          case 34: break;
          case 8:
            { debugToken(sym.UNIDAD, yytext()); return symbol(sym.UNIDAD, yytext());
            }
          // fall through
          case 35: break;
          case 9:
            { return symbol(sym.LBRACK);
            }
          // fall through
          case 36: break;
          case 10:
            { return symbol(sym.RBRACK);
            }
          // fall through
          case 37: break;
          case 11:
            { String t = yytext().trim();
                                    debugToken(sym.TEXT, t);
                                    return symbol(sym.TEXT, t);
            }
          // fall through
          case 38: break;
          case 12:
            { debugToken(sym.NL, null);
                                    yybegin(YYINITIAL);
                                    return symbol(sym.NL);
            }
          // fall through
          case 39: break;
          case 13:
            { debugToken(sym.STRING, yytext());
                                    return symbol(sym.STRING, yytext().substring(1, yytext().length()-1));
            }
          // fall through
          case 40: break;
          case 14:
            { debugToken(sym.STEPNUM, yytext());
                                    yybegin(S_VAL);
                                    return symbol(sym.STEPNUM, yytext().substring(0, yytext().length()-1));
            }
          // fall through
          case 41: break;
          case 15:
            { debugToken(sym.OBS, null); yybegin(S_VAL); return symbol(sym.OBS);
            }
          // fall through
          case 42: break;
          case 16:
            { debugToken(sym.PASOS, null); return symbol(sym.PASOS);
            }
          // fall through
          case 43: break;
          case 17:
            { debugToken(sym.TIPO, null); yybegin(S_VAL); return symbol(sym.TIPO);
            }
          // fall through
          case 44: break;
          case 18:
            { debugToken(sym.AGUSTO, "a gusto"); return symbol(sym.AGUSTO, "a gusto");
            }
          // fall through
          case 45: break;
          case 19:
            { debugToken(sym.ORIGEN, null); yybegin(S_VAL); return symbol(sym.ORIGEN);
            }
          // fall through
          case 46: break;
          case 20:
            { debugToken(sym.RECETA, null); return symbol(sym.RECETA);
            }
          // fall through
          case 47: break;
          case 21:
            { debugToken(sym.TIEMPO, null); yybegin(S_VAL); return symbol(sym.TIEMPO);
            }
          // fall through
          case 48: break;
          case 22:
            { debugToken(sym.CALORIAS, null); yybegin(S_VAL); return symbol(sym.CALORIAS);
            }
          // fall through
          case 49: break;
          case 23:
            { debugToken(sym.PORCIONES, null); yybegin(S_VAL); return symbol(sym.PORCIONES);
            }
          // fall through
          case 50: break;
          case 24:
            { debugToken(sym.CATEGORIAS, null); return symbol(sym.CATEGORIAS);
            }
          // fall through
          case 51: break;
          case 25:
            { debugToken(sym.DIFICULTAD, null); yybegin(S_VAL); return symbol(sym.DIFICULTAD);
            }
          // fall through
          case 52: break;
          case 26:
            { debugToken(sym.INGREDIENTES, null); return symbol(sym.INGREDIENTES);
            }
          // fall through
          case 53: break;
          case 27:
            { debugToken(sym.RELACIONADAS, null); return symbol(sym.RELACIONADAS);
            }
          // fall through
          case 54: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
