
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RBRACK = 15;
  public static final int PASOS = 4;
  public static final int DIFICULTAD = 10;
  public static final int ORIGEN = 9;
  public static final int WORD = 22;
  public static final int CALORIAS = 7;
  public static final int INGREDIENTES = 3;
  public static final int RELACIONADAS = 12;
  public static final int LBRACK = 14;
  public static final int DOSP = 17;
  public static final int OBS = 13;
  public static final int CATEGORIAS = 8;
  public static final int TIPO = 11;
  public static final int STRING = 19;
  public static final int COMA = 16;
  public static final int EOF = 0;
  public static final int AGUSTO = 25;
  public static final int UNIDAD = 21;
  public static final int TIEMPO = 5;
  public static final int CANTIDAD = 20;
  public static final int error = 1;
  public static final int STEPNUM = 24;
  public static final int TEXT = 23;
  public static final int PORCIONES = 6;
  public static final int RECETA = 2;
  public static final int NL = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RECETA",
  "INGREDIENTES",
  "PASOS",
  "TIEMPO",
  "PORCIONES",
  "CALORIAS",
  "CATEGORIAS",
  "ORIGEN",
  "DIFICULTAD",
  "TIPO",
  "RELACIONADAS",
  "OBS",
  "LBRACK",
  "RBRACK",
  "COMA",
  "DOSP",
  "NL",
  "STRING",
  "CANTIDAD",
  "UNIDAD",
  "WORD",
  "TEXT",
  "STEPNUM",
  "AGUSTO"
  };
}

